version: '3'

services:
  nginx:
    image: nginx:1.0
    container_name: nginx
    build:
      context: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

  mariadb:
    image: mariadb:1.0
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    ports:
      - 3306:3306
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress:1.0
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

  redis:
    image: redis:1.0
    container_name: redis
    build:
      context: ./requirements/bonus/redis/
    networks:
      - inception
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
