version: '3.5'

services:
  nginx:
    image: nginx:1.0
    container_name: nginx
    build:
      context: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception-network
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always

  mariadb:
    image: mariadb:1.0
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        DB_ROOT: ${DB_ROOT}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    networks:
      - inception-network
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress:1.0
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: ${DB_HOST}
    depends_on:
      - mariadb
      - redis
    networks:
      - inception-network
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always

  redis:
    image: redis:1.0
    container_name: redis
    build:
      context: ./requirements/bonus/redis/
    networks:
      - inception-network
    restart: always

  ftp:
    image: ftp:1.0
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp/
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    depends_on:
      - wordpress
    ports:
      - "21:21"
    networks:
      - inception-network
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always

  adminer:
    image: adminer:1.0
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer/
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception-network
    restart: always

volumes:
  wordpress-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  mariadb-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception-network:
        driver: bridge
