version: '3.5'

networks:
    inception-network:
      name: inception-network
      driver: bridge

volumes:
  mariadb-volume:
    name: mariadb-volume
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/mariadb

  wordpress-volume:
    name: wordpress-volume
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/wordpress

services:
  nginx:
    depends_on:
      - wordpress
    image: nginx:1.0
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - inception-network
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always

  mariadb:
    image: mariadb:1.0
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    networks:
      - inception-network
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - mariadb
      - redis
    image: wordpress:1.0
    container_name: wordpress
    build: ./requirements/wordpress/
    env_file:
      - .env
    networks:
      - inception-network
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always

  redis:
    image: redis:1.0
    container_name: redis
    build: ./requirements/bonus/redis/
    networks:
      - inception-network
    restart: always

  ftp:
    image: ftp:1.0
    container_name: ftp
    build: ./requirements/bonus/ftp/
    env_file:
      - .env
    ports:
      - "21:21"
    networks:
      - inception-network
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always

  adminer:
    image: adminer:1.0
    container_name: adminer
    build: ./requirements/bonus/adminer/
    ports:
      - "8080:8080"
    networks:
      - inception-network
    restart: always

  resume:
    image: resume:1.0
    container_name: resume
    build: ./requirements/bonus/resume/
    ports:
      - "80:80"
    networks:
      - inception-network
    restart: always

  portainer:
    image: portainer:1.0
    container_name: portainer
    build: ./requirements/bonus/portainer/
    ports:
      - "9443:9443"
    networks:
      - inception-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
