version: '3'

services:
  nginx:
    # depends_on:
    #   - wordpress
    build: ./requirements/nginx/
    image: nginx:1.0
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - /home/aamajane/simple_docker_nginx_html/public/html:/var/www/