version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    # depends_on:
    #   - wordpress
    ports:
      - 443:443
    volumes:
      - /home/aamajane/simple_docker_nginx_html/public/html:/var/www/
    restart: always